src/category/urls.py
from django.urls import path

from . import views
app_name='new'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('<int:id>/', views.view, name='info'),
    path('category/', views.category, name='category'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('category.urls')),
    path('', include('category.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/category/models.py
from django.db import models

class Catalog(models.Model):
    name = models.CharField(max_length=200)
    created_date = models.DateTimeField(auto_now=True, blank=True)
    update_date = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Catalog"
        verbose_name_plural = "Cataloglar"

class News(models.Model):
    name = models.CharField(max_length=200)
    info = models.TextField()
    category = models.ForeignKey(Catalog, on_delete=models.CASCADE, null=True)
    photo = models.ImageField(max_length=200, blank=True, upload_to='news')
    created_date = models.DateTimeField(auto_now=True, blank=True)
    update_date = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Yangilik"
        verbose_name_plural = "Yangiliklar"
class Contact(models.Model):
    info = models.TextField(null=True)
    name = models.CharField(max_length=200)
    adress = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    office = models.CharField(max_length=200, null=True)
    created_date = models.DateTimeField(auto_now=True, blank=True)
    update_date = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Contact"
        verbose_name_plural = "Contactlar"

src/category/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
# Create your views here.

def index(request):
    catalogs = Catalog.objects.all()
    news = News.objects.all()
    context = {'catalogs': catalogs, 'news': news}
    return render(request, 'index.html', context)

def contact(request):
    contacts = Contact.objects.get(pk=1)
    context = {'contacts': contacts}
    return render(request, 'contact.html', context)

def view(request, id):
    news = News.objects.all()
    try:
        view = News.objects.get(pk=id)
    except News.DoesNotExist:
        view = None
    context= {'view': view,
              'news': news}
    return render(request, 'view.html', context)
def category(request):
    catalogs = Catalog.objects.all()
    news = News.objects.all()
    context = {'catalogs': catalogs, 'news': news}
    return render(request, 'category.html', context)

src/templates/category.html
{% extends "main.html" %}
{% block title %} Home {% endblock %}
{% block content %}
{% load static %}
	<a href="#" class="bigrek"></a>
	<div class="container wrapper">
		<div class="longrek"></div>
		<div class="clearfix"></div>
		
		<ol class="breadcrumb">
			<li><a href="#">Главная</a></li>
			<li class="active">Политика</li>
		</ol>
		<div class="row">
			<div class="col-md-8 col-xs-12">
				<div class="cat_title">Политика</div>
				<div class="big_fav pop_cat">
				<div id="bigfav" class="carousel slide" data-ride="carousel">
					<div class="carousel-inner" role="listbox">
						<div class="item active">
								{% for new in news %}
							<img src="{{ new.photo.url }}" alt="...">
								{% endfor %}
								<a href="#">
									<div class="carousel-caption">
										<div class="caption_pos">
											{% for new in news %}
											{% if new.category_id == 8 and new.id == 21%}
											<div class="type_news">ПОЛИТИКА</div>
											<div class="title">{{ new.info }}</div>
											<span class="date">{{ new.created_date|date:'d.m.Y' }}</span>
											{% endif %}
											{% endfor %}
										</div>
									</div>
								</a>
						</div>
					</div>
					<div class="control">
					<a class="left carousel-control" href="#bigfav" role="button" data-slide="prev">
						<i class="fa fa-angle-left"></i>
					</a>
					<a class="right carousel-control" href="#bigfav" role="button" data-slide="next">
						<i class="fa fa-angle-right"></i>
					</a>
					</div>
				</div>
			</div>
				<div class="news_box">
					{% for new in news %}
					{% if new.category_id == 8%}
					<div class="cat_news">
						<div class="cat_img"><img src="{{ new.photo.url }}" alt=""></div>
						<a href="{% url 'new:info' new.id %}">{{ new.name }}</a>
						<p>{{ new.info }}</p>
						<span class="date">{{ new.created_date|date:'d.m.Y' }}</span>
						<span class="news_type"><i class="fa fa-pencil"></i> Общество</span>

					</div>
							{% endif %}
							{% endfor %}
					<nav aria-label="Page navigation">
						<ul class="pagination">
							<li>
								<a href="#" aria-label="Previous">
									<span aria-hidden="true">&laquo;</span>
								</a>
							</li>
							<li><a href="#">1</a></li>
							<li><a href="#">2</a></li>
							<li><a href="#">3</a></li>
							<li><a href="#">4</a></li>
							<li><a href="#">5</a></li>
							<li>
								<a href="#" aria-label="Next">
									<span aria-hidden="true">&raquo;</span>
								</a>
							</li>
						</ul>
					</nav>											
				</div>
			</div>
			<div class="col-md-4 col-xs-12">
				<div class="head_title">Свежие новости</div>
				<div id="listnews" class="carousel slide listnews" data-ride="carousel">
					<div class="news_box">
						<div class="carousel-inner" role="listbox">
							<div class="item active">
								<ul class="list_news">
									{% for new in news %}
									{% if new.category_id == 7 %}
									<li>
										<div class="list_img"><img src="{{ new.photo.url }}" alt=""></div>
										<a href="{% url 'new:info' new.id %}">{{ new.info }}</a>
										<span class="date">{{ new.created_date|date:'d.m.Y' }}</span>
										<span class="news_type"><i class="fa fa-pencil"></i> Общество</span>
									</li>
										{% endif %}
								{% endfor %}
								</ul>
							</div>
						</div>
					</div>
					<div class="indi_box">
						<ol class="carousel-indicators">
							<li data-target="#listnews" data-slide-to="0" class="active"></li>
							<li data-target="#listnews" data-slide-to="1"></li>
						</ol>
					</div>				
				</div>
				
				<div class="news_box rek">
					<div class="rek_right">
						
					</div>
				</div>
				<div class="subscribe">
					<div class="title">Подписывайся на <b>1news.uz</b></div>
					<form action="">
						<div class="input-group">
							<input type="text" name="email" placeholder="Email">
							<button class="submit">Подписываться</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

src/templates/contact.html
{% extends "main.html" %}
{% block title %} Home {% endblock %}
{% block content %}
{% load static %}
<a href="#" class="bigrek"></a>
	<div class="container wrapper">
		<div class="longrek"></div>
		<div class="clearfix"></div>

		<ol class="breadcrumb">
			<li><a href="#">Главная</a></li>
			<li class="active">Контакты</li>
		</ol>
		<div class="row">
			<div class="col-md-5 col-xs-12">
				<div class="cat_title">Контакты</div>
				<div class="con_info">{{ contacts.info}} </div>
				<ul class="contact">

					<li><i class="fa fa-map-marker">{{ contacts.adress}}</i></li>
					<li><i class="fa fa-print"></i> {{ contacts.office }}</li>
					<li><i class="fa fa-mobile"></i> {{ contacts.phone }}</li>
					<li><i class="fa fa-envelope"></i>  {{ contacts.email }} </li>

				</ul>
				<div class="feedback">
					<div class="title">Обратная связь</div>
					<form action="#">
						<input type="text" name="name" placeholder="Ваше имя">
						<input type="text" name="name" placeholder="Ваше email">
						<textarea name="" id="" cols="30" rows="10" placeholder="Сообщение"></textarea>
						<button class="btn submit">Отправить</button>
					</form>
				</div>
			</div>
			<div class="col-md-7 col-xs-12">
				<div class="con_img">
					<img src="{% static 'img/contact.jpg' %}" alt="">
				</div>
				<div class="map"></div>
			</div>
		</div>
	</div>
{% endblock %}

src/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %} Home {% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/media.css' %}">
</head>
<body>
	<div class="topheader">
		<div class="container">
			<ul class="menu">
				<li><a href="#">о нас</a></li>
				<li><a href="#">редакционная</a></li>
				<li><a href="#">политика</a></li>
				<li><a href="#">контакты</a></li>
			</ul>
			<ul class="kurs">
				<li>1 USD = 3243.89</li>
				<li>1 EUR = 3419.18</li>
				<li>1 RUB = 53.48</li>
			</ul>
			<ul class="lang">

				<li class="active"><a href="#">Ру</a></li>
				<li><a href="">O'z</a></li>
				<li><a href="">Уз</a></li>
			</ul>
			<ul class="social">
				<li><a href="#"><span class="fa fa-facebook-f"></span></a></li>
				<li><a href="#"><span class="fa fa-twitter"></span></a></li>
				<li><a href="#"><span class="fa fa-linkedin"></span></a></li>
				<li><a href="#"><span class="fa fa-telegram"></span></a></li>
				<li><a href="#"><span class="fa fa-google-plus"></span></a></li>
				<li><a href="#"><span class="fa fa-rss"></span></a></li>
			</ul>
		</div>
	</div>
	<nav class="navbar">
  	<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#"><img src="{% static 'img/logo.png' %}" alt=""></a>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<i class="fa fa-close"></i>
				</button>
				<ul class="nav navbar-nav">
					<li class="active"><a href="#">экономика</a></li>
					<li><a href="#">политика</a></li>
					<li><a href="#">общество</a></li>
					<li><a href="#">культура</a></li>
					<li><a href="#">спорт</a></li>
					<li><a href="#">в мире</a></li>
					<li><a href="#">нно</a></li>
				</ul>
				<button type="button" class="btn navbar-right search_btn hidden-xs"><i class="fa fa-search"></i></button>
				<form action="" method="get" id="search" class="navbar-form navbar-right search_btn_box hidden-xs">
        <button class="btn btn-default" type="button">
          <span><i class="fa fa-search"></i></span></button>
        <div class="input-group">
          <input type="text" name="v" id="searchName" class="form-control" placeholder="Поиск..." required="">
          <input type="submit" hidden="">
        </div>
        <button type="button" class="btn  search_btn_close hidden-xs active"><i class="fa fa-close"></i></button>
      </form>
			</div>
		</div>
	</nav>
	<a href="#" class="bigrek"></a>
	{% block content %}  {% endblock %}
	<div class="foot_about">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-xs-12"><img src="{% static 'img/logo.png' %}" alt="" class="logo"></div>
				<div class="col-md-6 col-xs-12">
					<div class="title">О нас</div>
					<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec</p>
				</div>
				<div class="col-md-3 col-xs-12 text-right">
					<ul class="social">
						<li><a href="#"><span class="fa fa-facebook-f"></span></a></li>
						<li><a href="#"><span class="fa fa-twitter"></span></a></li>
						<li><a href="#"><span class="fa fa-linkedin"></span></a></li>
						<li><a href="#"><span class="fa fa-telegram"></span></a></li>
						<li><a href="#"><span class="fa fa-google-plus"></span></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<footer>
		<div class="container">
			<ul class="menu">
				<li><a href="#">о нас</a></li>
				<li><a href="#">контакты</a></li>
				<li><a href="#">редакционная</a></li>
				<li><a href="#">ОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ</a></li>
				<li><a href="#">СОГЛАШЕНИЕ</a></li>
			</ul>
			<div class="copyright">
				© COPYRIGHT 2017 BY <a href="#">md</a>
			</div>
		</div>
	</footer>



	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

src/templates/view.html
{% extends "main.html" %}
{% block title %} Home {% endblock %}
{% block content %}
{% load static %}
<a href="#" class="bigrek"></a>
	<div class="container wrapper">
		<div class="longrek"></div>
		<div class="clearfix"></div>
		<ol class="breadcrumb">
			<li><a href="#">Главная</a></li>
			<li><a href="#">Культура</a></li>
			<li class="active">«Ожидание» — весенняя коллекция для девушек в «особом» положении</li>
		</ol>
		<div class="row">
			<div class="col-md-8 col-xs-12">
				<div class="view_img"><img src="{{ view.photo.url }}" alt=""></div>
				<div class="news_box view">
					<div class="view_title">{{ view.name }}</div>
					<span class="date">{{ view.created_date|date:'d.m.Y' }}</span>
					<span class="news_type"><i class="fa fa-pencil"></i> Общество</span>
					<div class="view_desc">
					<p>{{ view.info }}</p>
					<p>{{ view.info }}</p>
					<p>{{ view.info }}</p>
					<div id="bigfav" class="carousel slide view_slide" data-ride="carousel">
						<div class="carousel-inner" role="listbox">
							<div class="item active">
								<img src="{{ view.photo.url }}" alt="...">
							</div>
							<div class="item">
								<img src="{% static 'img/news1.jpg' %}" alt="...">
							</div>
							<div class="item">
								<img src="{% static 'img/news2.jpg' %}" alt="...">
							</div>
						</div>
						<div class="control">
						<a class="left carousel-control" href="#bigfav" role="button" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a class="right carousel-control" href="#bigfav" role="button" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
						</div>
					</div>
				<p>{{ view.info }}</p>
				</div>
				<ul class="tag">
					<li><a href="#">#мода</a></li>
					<li><a href="#">#новости</a></li>
					<li><a href="#">#тег1</a></li>
					<li><a href="#">#тег2</a></li>
					<li><a href="#">#тег3</a></li>
					<li><a href="#">#тег4</a></li>
				</ul>
				<div class="nav_news">
					<a href="#" class="prev_news text-right">
						<i class="fa fa-angle-left"></i>
						{{ view.name }}
					</a>
					<a href="#" class="next_news">
						Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
						<i class="fa fa-angle-right"></i>
					</a>
					<div class="clearfix"></div>
				</div>
				<div class="comment">
					<div class="title">Комменты</div>
					<ul>
						<li>
							<div class="com_img"><img src="{% static 'img/ava.jpg' %}" alt=""></div>
							<div class="com_info">
								<div class="author">Adam Levine</div>
								<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>
								<div class="date">02.02.2017</div>
								<hr>
							</div>
							<ul class="sub">
								<li>
									<div class="com_img"><img src="{% static 'img/ava.jpg' %}" alt=""></div>
									<div class="com_info">
										<div class="author">Adam Levine</div>
										<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>
										<div class="date">02.02.2017</div>
										<hr>
									</div>

								</li>
								<li>
									<div class="com_img"><img src="{% static 'img/ava.jpg' %}" alt=""></div>
									<div class="com_info">
										<div class="author">Adam Levine</div>
										<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>
										<div class="date">02.02.2017</div>
										<hr>
									</div>

								</li>
							</ul>
						</li>
						<li>
									<div class="com_img"><img src="{% static 'img/ava.jpg' %}" alt=""></div>
									<div class="com_info">
										<div class="author">Adam Levine</div>
										<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>
										<div class="date">02.02.2017</div>
										<hr>
									</div>

								</li>
								<li>
									<div class="com_img"><img src="{% static 'img/ava.jpg' %}" alt=""></div>
									<div class="com_info">
										<div class="author">Adam Levine</div>
										<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>
										<div class="date">02.02.2017</div>
										<hr>
									</div>

								</li>
					</ul>
					<button class="btn add_comment">Добавить комментарий</button>
					<div class="add_info">Приветствуются интересные и осмысленные комментарии по теме материала.</div>
				</div>
				</div>
			</div>
			<div class="col-md-4 col-xs-12">
				<div class="head_title">Свежие новости</div>
				<div id="listnews" class="carousel slide listnews" data-ride="carousel">
					<div class="news_box">
						<div class="carousel-inner" role="listbox">
							<div class="item active">
								<ul class="list_news">
									{% for new in news %}
									{% if new.category_id == 7 %}
									<li>
										<div class="list_img"><img src="{{ new.photo.url }}" alt=""></div>
										<a href="{% url 'new:info' new.id %}">{{ new.info }}</a>
										<span class="date">{{ new.created_date|date:'d.m.Y' }}</span>
										<span class="news_type"><i class="fa fa-pencil"></i> Общество</span>
									</li>
										{% endif %}
								{% endfor %}
								</ul>
							</div>
						</div>
					</div>
					<div class="indi_box">
						<ol class="carousel-indicators">
							<li data-target="#listnews" data-slide-to="0" class="active"></li>
							<li data-target="#listnews" data-slide-to="1"></li>
						</ol>
					</div>
				</div>

				<div class="news_box rek">
					<div class="rek_right">

					</div>
				</div>
				<div class="subscribe">
					<div class="title">Подписывайся на <b>1news.uz</b></div>
					<form action="">
						<div class="input-group">
							<input type="text" name="email" placeholder="Email">
							<button class="submit">Подписываться</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}